### ISSUE TITLE
Investigate API logging when in a pod

### ISSUE THREAD

**Issue by robert-clegg-tessella** [ukaea/piezo#35]
Configuration and retrieval of web app logging may need to be different when the app is deployed in a pod, rather than hosted on a server. Investigate how that should be managed and write up findings in the wiki.

**Comment by oliver-tarrant-tessella** [comment]
Our investigation outlined the two main ways to expose logs from the Piezo web app when running on the Kubernetes cluster. These have not been implemented due to time constraints and other currently more high priority issues but each method has been recorded in the Wiki with links to the relevant documentation. https://github.com/ukaea/piezo/wiki/Logging
